apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpp-server-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:vpp-server
  # name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: vpp-server
