apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpp-server

resources:
  - Namespace.yml
  - NetworkAttachmentDefinition.yml
  - Deployment.yml
  - ClusterRole.yml
  - ClusterRoleBinding.yml
  - SCC.yml

generatorOptions:
  disableNameSuffixHash: true
