apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan0
spec:
  config:  |-
    {
    "cniVersion": "0.3.1",
    "name": "macvlan0",
    "type": "macvlan",
    "master": "$MACVLAN_MASTER",
    "linkInContainer": false,
    "mode": "bridge"
    }
